version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Getting latest gb file
      - wget http://download.geofabrik.de/europe/great-britain-latest.osm.pbf
      - echo Running osrm-extract
      - osrm-extract -p /opt/car.lua great-britain-latest.osm.pbf
      - echo Running osrm-partition
      - osrm-partition great-britain-latest.osrm
      - echo Running osrm-customize
      - osrm-customize great-britain-latest.osrm
      - echo Done
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - great-britain-latest.osrm
